### PR TITLE
Fix #541: Allow @sha256 digest for tags in FROM

### LINKED ISSUE #541: Allow @sha256 digest for tags in FROM
When I try to use a digest tag in my Dockerfile FROM: such as "FROM: mytomcat@sha256:b61b1b823ec66a2875c44572885fa332990b3aa0055ed50abf7f94837c9f7925" I get this:

[ERROR] Failed to execute goal io.fabric8:docker-maven-plugin:0.15.14:build (docker-build) on project kestrel-docker: Execution docker-build of goal io.fabric8:docker-maven-plugin:0.15.14:build failed: Given repository name 'mytomcat@sha256:b61b1b823ec66a2875c44572885fa332990b3aa0055ed50abf7f94837c9f7925' is invalid:
[ERROR] \* image part 'mytomcat@sha256' doesn't match allowed pattern '(?:(?:[a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9-]_[a-zA-Z0-9])(?:(?:.(?:[a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9-]_[a-zA-Z0-9]))+)?(?::[0-9]+)?/)?[a-z0-9]+(?:(?:[._]|__|[-]_)[a-z0-9]+)_(?:/[a-z0-9]+(?:(?:[._]|__|[-]_)[a-z0-9]+)_)?'

I see various mentions in docker re: digest usage and our docker-compose.yml uses it just fine. Do the regex's need to be updated?

### PR DESCRIPTION
**Pull request by rohanKanojia**
Fixes #541

### CODE REVIEW

File: src/main/java/io/fabric8/maven/docker/util/ImageName.java [hunk 1]
```diff
@@ -60,38 +63,46 @@ public ImageName(String fullName, String givenTag) {
...
-            if (isRegistry(parts[0])) {
-                registry = parts[0];
-                if (parts.length > 2) {
-                    user = parts[1];
-                    repository = joinTail(parts);
+
+        if(fullName.contains("@sha256")) { // Of it contains digest
+            String[] digestParts = fullName.split("@");
+            digest = digestParts[1];
+            repository = digestParts[0];
```
Comment (rhuss) [inline src/main/java/io/fabric8/maven/docker/util/ImageName.java]: What if the user specified a registry/respository@sha245:digest ? What happens with the registry ?

File: src/test/java/io/fabric8/maven/docker/util/ImageNameTest.java [hunk 2]
```diff
@@ -125,6 +125,8 @@ public void testRegistryNamingExtended() throws Exception {
                 new ImageName("docker.jolokia.org/org/jolokia/jolokia_demo").getFullName("another.registry.org"));
         assertEquals("docker.jolokia.org/org/jolokia/jolokia_demo:latest",
                 new ImageName("docker.jolokia.org/org/jolokia/jolokia_demo").getFullName(null));
+        assertEquals("docker.jolokia.org/org/jolokia/jolokia_demo@sha256:2781907cc3ae9bb732076f14392128d4b84ff3ebb66379d268e563b10fbfb9da",
+                new ImageName("docker.jolokia.org/org/jolokia/jolokia_demo@sha256:2781907cc3ae9bb732076f14392128d4b84ff3ebb66379d268e563b10fbfb9da").getFullName(null));
```
Comment (rhuss) [inline src/test/java/io/fabric8/maven/docker/util/ImageNameTest.java]: Could add a check here that ImageName.getRegistry() returns indeed docker.jolokia.org ? (i doubt that)

Comment (rohanKanojia) [reply src/test/java/io/fabric8/maven/docker/util/ImageNameTest.java]: Yep, you're right
